default: &default
  adapter: postgresql
  encoding: unicode
  database: ku_db
  host: localhost
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: ku_db
  host: localhost
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: ku_db
  host: localhost
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: ku_db
  host: localhost
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
