# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9135432e33a19b87db51cdf42fb52e2bd070ebc84f98cfb16f19cd9e52532de81ec9ba8991401cdc954e5e734b072156ed761f886fbf8c3d2ba236c46b5cdebf

test:
  secret_key_base: 51d494d6eaed86f7c37cc0b0154884bd5d01bfbc26c29d1277d5dce1a392367394dc9d90881424907e25768ba0d58f6d54301995cb8eb42b0e7ca729830cf4f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
